syntax = "proto3";

package tree;

service TreeReadService {
  rpc GetRootTree(GetRootTreeRequest) returns (Tree);
  rpc GetNode(GetNodeRequest) returns (Node);
}

message GetRootTreeRequest {
  string node_id = 1;
}

message GetNodeRequest {
  string node_id = 1;
}

message Tree {
  string id = 1;
  string title = 2;
  repeated Tree children = 3;
  string created_at = 4;
  string updated_at = 5;
  optional string deleted_at = 6;
}

message Node {
  string id = 1;
  string title = 2;
  optional string parent_id = 3;
  string created_at = 4;
  string updated_at = 5;
  optional string deleted_at = 6;
}