@startuml
actor :Администратор: as admin
actor :Пользователь: as user
actor :Планировщик парсинга: as puser

"Создание узлов иерархий" as (cie)
"Перенос поддеревьев между узлами" as (mie)
"Удаление узлов и целых иерархий" as (die)
"Управление пользователями" as (usm)

"Получение полных деревьев и поддеревьев" as (seie)
"CRUD операции с документами" as (crudd)
"Привязка документов к узлам иерархии" as (atd)
"Загрузка/удаление файлов документов" as (lod)
"Установление связей между документами" as (lid)
"Поиск по названию, тегам и содержимому" as (sead)

"Парсинг содержимого файлов" as (pa)

user --> (seie)
user --> (crudd)
user --> (atd)
user --> (lod)
user --> (lid)
user --> (sead)

admin --|> user
admin --> (cie)
admin --> (mie)
admin --> (die)
admin --> (usm)

admin --|> puser
puser --> (pa)
@enduml